github: owenh000
liberapay: owenh
ko_fi: owenh
patreon: owenh
issuehunt: owenh000
custom:
  - "https://flattr.com/@owenh"
  - "https://paypal.me/owenh000"
  - "https://www.blockchain.com/btc/address/19b7CCBUqmCHkGDD8iCsRpKu34vrv3c7Lp"
  - "https://etherscan.io/address/0xfe6f4bafc497afc2777183cc531004744469f196"
  - "https://owenh.net/support"
